/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Model.*;
import Controller.*;
import com.sun.org.apache.bcel.internal.classfile.Code;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import static javafx.scene.input.KeyCode.T;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class HomeFrm extends javax.swing.JDialog implements View{

    /**
     * Creates new form HomeFrm
     */
    private List<KhachHang> khachHangList;
    private List<MatHang> matHangList;
    private List<QLBH> qlList;
    private DefaultTableModel khachHangDefaultTableModel;
    private DefaultTableModel matHangDefaultTableModel;
    private DefaultTableModel qlDefaultTableModel;
    private DefaultTableModel tongTBDefaultTableModel;
    private int lastKH,lastMH;
    private FileIO file;
    public HomeFrm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setLocationRelativeTo(null);
        initComponents();
        khachHangList = new ArrayList<>();
        matHangList = new ArrayList<>();
        qlList = new ArrayList<>();
        khachHangDefaultTableModel = (DefaultTableModel) khachHangTb.getModel();
        matHangDefaultTableModel = (DefaultTableModel) matHangTb.getModel();
        qlDefaultTableModel = (DefaultTableModel) qlTb.getModel();
        tongTBDefaultTableModel = (DefaultTableModel) tongTb.getModel();
        file = new FileIO();
        readHang();
        readKhach();
        readQL();
        loadDataToComboBox();
    }
     public void addHang(MatHang l){
        matHangList.add(l);
        this.showData(matHangList,matHangDefaultTableModel);
        loadDataToComboBox();
        file.saveToFile((ArrayList) matHangList, "MH.TXT");
    }
    public void addKhach(KhachHang l){
        khachHangList.add(l);
        loadDataToComboBox();
        this.showData(khachHangList,khachHangDefaultTableModel);
        file.saveToFile((ArrayList) khachHangList,"KH.TXT");
    }
    public void addQL( QLBH l){
        qlList.add(l);
        this.showData(qlList, qlDefaultTableModel); 
       file.saveToFile((ArrayList) qlList, "QLBH.TXT");
    }
    private void readHang(){
        matHangList = file.readFromFile("MH.TXT");
        this.showData(matHangList, matHangDefaultTableModel);
        
    }
    private void readKhach(){
        khachHangList = file.readFromFile("KH.TXT");
        this.showData(khachHangList, khachHangDefaultTableModel);
    }
    private void readQL(){
        qlList = file.readFromFile("QLBH.TXT");
        this.showData(qlList, qlDefaultTableModel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        matHangTb = new javax.swing.JTable();
        tenHangF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nhomHangF = new javax.swing.JTextField();
        giaBanF = new javax.swing.JTextField();
        themHangBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        khachHangTb = new javax.swing.JTable();
        hoTenF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        diaChiF = new javax.swing.JTextField();
        soDtF = new javax.swing.JTextField();
        themKhachHangF = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        qlTb = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        khachCB = new javax.swing.JComboBox<>();
        mhCB = new javax.swing.JComboBox<>();
        soLuongF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tongTb = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        khachCB1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        tongLb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        matHangTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ma hang", "ten Hang", "nhom hang", "gia ban"
            }
        ));
        jScrollPane1.setViewportView(matHangTb);

        jLabel1.setText("ten hang");

        jLabel2.setText("nhom hang");

        jLabel3.setText("gia ban");

        giaBanF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giaBanFActionPerformed(evt);
            }
        });

        themHangBtn.setText("them");
        themHangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themHangBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(giaBanF, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(nhomHangF)
                    .addComponent(tenHangF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(themHangBtn)
                .addGap(243, 243, 243))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenHangF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nhomHangF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(giaBanF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(themHangBtn)
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("Mat Hang", jPanel1);

        khachHangTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ma KH", "ho ten", "dia chi", "so Dt"
            }
        ));
        jScrollPane2.setViewportView(khachHangTb);

        jLabel4.setText("ho ten");

        jLabel5.setText("dia chi");

        jLabel6.setText("so Dt");

        soDtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soDtFActionPerformed(evt);
            }
        });

        themKhachHangF.setText("them");
        themKhachHangF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themKhachHangFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(soDtF, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(diaChiF)
                    .addComponent(hoTenF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(themKhachHangF)
                .addGap(243, 243, 243))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoTenF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(diaChiF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(soDtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(themKhachHangF)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Khach Hang", jPanel2);

        qlTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ho ten", "mat hang", "so luong"
            }
        ));
        jScrollPane3.setViewportView(qlTb);
        if (qlTb.getColumnModel().getColumnCount() > 0) {
            qlTb.getColumnModel().getColumn(0).setHeaderValue("ho ten");
        }

        jLabel7.setText("khach hang");

        jLabel8.setText("mat hang");

        jLabel9.setText("soluong");

        khachCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khachCBActionPerformed(evt);
            }
        });

        jButton1.setText("them");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("xep theo hang");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("xep theo ten");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soLuongF, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(mhCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(khachCB, 0, 229, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(khachCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(mhCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(soLuongF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(23, 23, 23)
                .addComponent(jButton1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quan Ly", jPanel3);

        tongTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "mat hang", "so luong"
            }
        ));
        jScrollPane4.setViewportView(tongTb);

        jLabel10.setText("khach hang");

        khachCB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khachCB1ActionPerformed(evt);
            }
        });

        jButton4.setText("tinh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tongLb.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tongLb)
                .addGap(45, 45, 45))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(jLabel10)
                            .addGap(44, 44, 44)
                            .addComponent(khachCB1, 0, 229, Short.MAX_VALUE)
                            .addGap(217, 217, 217)))
                    .addGap(3, 3, 3)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addComponent(tongLb)
                .addGap(62, 62, 62)
                .addComponent(jButton4)
                .addGap(100, 100, 100))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(khachCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(190, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tinh gia", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void giaBanFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giaBanFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giaBanFActionPerformed

    private void themHangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themHangBtnActionPerformed
        String ten = tenHangF.getText();
        String nhom = nhomHangF.getText();
        String gia = giaBanF.getText();
        if(ten.isEmpty()|| nhom.isEmpty()|| gia.isEmpty()){
            JOptionPane.showMessageDialog(null, "khong de trong");

        }
        else{
            int n;
            try{
                n = Integer.parseInt(gia);
                MatHang l = new MatHang(ten,nhom,n);
                this.addHang(l);
            }
            catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "gia phai la so");

            }
        }
        // TODO add your handling code here:
        
    }//GEN-LAST:event_themHangBtnActionPerformed

    private void soDtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soDtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soDtFActionPerformed

    private void themKhachHangFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themKhachHangFActionPerformed
        String tenKhach = hoTenF.getText();
        String diaChi = diaChiF.getText();
        String soDt = soDtF.getText();
        if(tenKhach.isEmpty()|| diaChi.isEmpty()||soDt.isEmpty()){
            JOptionPane.showMessageDialog(null, "khong de trong");

        }
        else{
            try{
                int n = Integer.parseInt(soDt);
                KhachHang l = new KhachHang(tenKhach,diaChi,n);
                this.addKhach(l);
            }
            catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "soDT phai la so");
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_themKhachHangFActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Collections.sort(qlList,(o1, o2) -> {
            return o1.getKhach().getHoTen().compareTo(o2.getKhach().getHoTen());
        });
        this.showData(qlList, qlDefaultTableModel);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void khachCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khachCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_khachCBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        KhachHang k = khachHangList.get(khachCB.getSelectedIndex());
        MatHang m = matHangList.get(mhCB.getSelectedIndex());
        try{
            int sl = Integer.parseInt(soLuongF.getText());
            QLBH l = new QLBH(k,m,sl);
            if(ktra(l)) JOptionPane.showMessageDialog(null, "nhap trung ");
            else{
                if(ktraSoluong(l)==true){
                   this.addQL(l);
                }
                else 
                   JOptionPane.showMessageDialog(null, "qua soluong");}
        }
        catch(NumberFormatException ex){}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Collections.sort(qlList, new Comparator<QLBH>() {
            @Override
            public int compare(QLBH o1, QLBH o2) {
                return o1.getHang().getTenHang().compareTo(o2.getHang().getTenHang());
                
                        }
        });
        this.showData(qlList, qlDefaultTableModel);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void khachCB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khachCB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_khachCB1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int tong =0;
        tongTBDefaultTableModel.setRowCount(0);
        for(QLBH i:qlList){
            String x= i.getHang().getMaHang()+"";
            if(x.equals(khachCB1.getItemAt(khachCB1.getSelectedIndex()))) {
               tongTBDefaultTableModel.addRow(new Object[]{i.getHang().getTenHang(),i.getSoLuong()});
               tong+=i.getHang().getGiaBan()*i.getSoLuong();
            }
            }
        tongLb.setText(tong+"");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HomeFrm dialog = new HomeFrm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField diaChiF;
    private javax.swing.JTextField giaBanF;
    private javax.swing.JTextField hoTenF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> khachCB;
    private javax.swing.JComboBox<String> khachCB1;
    private javax.swing.JTable khachHangTb;
    private javax.swing.JTable matHangTb;
    private javax.swing.JComboBox<String> mhCB;
    private javax.swing.JTextField nhomHangF;
    private javax.swing.JTable qlTb;
    private javax.swing.JTextField soDtF;
    private javax.swing.JTextField soLuongF;
    private javax.swing.JTextField tenHangF;
    private javax.swing.JButton themHangBtn;
    private javax.swing.JButton themKhachHangF;
    private javax.swing.JLabel tongLb;
    private javax.swing.JTable tongTb;
    // End of variables declaration//GEN-END:variables

    @Override
    public <T> void showData(List<T> list, DefaultTableModel model) {
        model.setRowCount(0);
        for(T t:list){
            if(t instanceof MatHang){
                MatHang l = (MatHang) t;
                model.addRow(new Object[] {l.getMaHang(),l.getTenHang(),l.getNhomHang(),l.getGiaBan()});
               l.setLastMaHang(l.getMaHang());
            }
            if(t instanceof KhachHang){
                KhachHang l = (KhachHang) t;
                model.addRow(new Object[] {l.getMaKH(),l.getHoTen(),l.getDiaChi(),l.getsDT()});
                l.setLastMaKH(l.getMaKH());
            }
            if (t instanceof QLBH){
                QLBH l = (QLBH) t;
                model.addRow(new Object[]{l.getKhach().getHoTen(),l.getHang().getTenHang(),l.getSoLuong()});
            }
        }
    }

    private void loadDataToComboBox() {
        khachCB.removeAllItems();
        mhCB.removeAllItems();
        for(KhachHang i:khachHangList){
            khachCB.addItem(i.getHoTen());
            khachCB1.addItem(i.getMaKH()+"");
        }
        for(MatHang i: matHangList){
            mhCB.addItem(i.getTenHang());
        }
    }
    private boolean ktra(QLBH l){
        for(QLBH i: qlList){
            if(l.getKhach().equals(i.getKhach())){
                 if(l.getHang().equals(i.getHang())){
                    return true;
                }
            }
        } 
        return false;
    }
    private boolean ktraSoluong(QLBH l) {
        int so=l.getSoLuong();
        for(QLBH i: qlList){
            if(l.getKhach().equals(i.getKhach())){
                 if(l.getHang().equals(i.getHang())){
                    i.setSoLuong(i.getSoLuong()+so);
                }
                so+=i.getSoLuong();
            }
        }
        
        if(so<=10) return  true;
        return false;
    }
}
